name: CJ
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23203
title: 'Cool website, bro'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f4e8'
    - '#cca78d'
    - '#160e03'
    - '#a57857'
    - '#533823'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
